//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHL_K22CNT3_lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LhlAccount
    {
        public int LhlId { get; set; }
        public string LhlUserName { get; set; }
        public string LhlPassword { get; set; }
        public string LhlFullName { get; set; }
        public string LhlEmail { get; set; }
        public string LhlPhone { get; set; }
        public Nullable<bool> LhlActive { get; set; }
    }
}
