//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeHoangLong_2210900037.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lhl_TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lhl_TacGia()
        {
            this.Lhl_Sach = new HashSet<Lhl_Sach>();
        }
    
        public string Lhl_MaTG { get; set; }
        public string Lhl_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lhl_Sach> Lhl_Sach { get; set; }
    }
}
