//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHLK22CNT3Lesson11_2210900037.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LhlK22CNT3_Lesson11Entities : DbContext
    {
        public LhlK22CNT3_Lesson11Entities()
            : base("name=LhlK22CNT3_Lesson11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LHLCategory> LHLCategories { get; set; }
        public virtual DbSet<LHLProduct> LHLProducts { get; set; }
    }
}
