//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHLK22CNT3Lesson11_2210900037.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LHLCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LHLCategory()
        {
            this.LHLProducts = new HashSet<LHLProduct>();
        }
        [Display(Name ="Mã Danh Mục")]
    
        public int LhlId { get; set; }

        [Display(Name = "Tên Danh Mục")]
        public string LhlCateName { get; set; }

        [Display(Name = "Trạng Thái")]
        public Nullable<bool> LhlStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LHLProduct> LHLProducts { get; set; }
    }
}
